/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.autumncode.dka2;

import org.testng.annotations.*;

import static org.testng.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        App.main(null);
    }
}
