/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.autumncode.dka2;

import org.testng.annotations.*;

public class MainInvocationTest {
    @Test
    public void appHasAGreeting() {
        MainInvocation.main(null);
    }
}
