/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.autumncode.dka2;

import com.autumncode.dka1.*;
import java.io.PrintWriter;

public class MainInvocation {
    public static void main(String[] args) {
        DKA dka=new BasicDKA(new PrintWriter(System.out));
        new DKA2().doOther();
    }
}
